export const ImageAssets = {
  avatar: require('./avatar.png'),
  notification: require('./notification.png'),
  add: require('./add.png'),
  multiarrow: require('./multiarrow.png'),
  coin: require('./icon-coin.png'),
  arrowLeft: require('./arrow-left-line.png'),
  successCard: require('./Subtract.png'),
  ribbons: require('./Ribbons.png'),
  success: require('./Icon Success.png'),
  received: require('./received.png'),
  pending: require('./pending.png'),
  building: require('./icon-building-bank.png'),
  arrowright: require('./arrowright.png'),
  transaction: require('./transaction.png'),
  activeTransaction: require('./activetransaction.png'),
  home: require('./home.png'),
  activeHome: require('./activehome.png'),
  back: require('./back.png'),
  mark: require('./mark.png'),
  registeration: require('./registeration.png'),
  hero: require('./hero.png'),
  user: require('./user.png'),
  splash: require('./splash-custom.png'),
};
